### PR TITLE
Adding data from gtfs2gps

### LINKED ISSUE #18: transfer gtfs samples from gtfs2gps

### PR DESCRIPTION
**Pull request by pedro-andrade-inpe**
Close #18. Adding Berlin, Fortaleza, and Porto Alegre data.

### CODE REVIEW

**Comment by pedro-andrade-inpe** [comment]
@dhersz, please do not merge yet

**Comment by pedro-andrade-inpe** [comment]
@dhersz the error in Mac was fixed (as well as in #11 after merging this PR). Please tell me if there is any additional issue here.

**Comment by dhersz** [comment]
Nice @pedro-andrade-inpe. 

The GitHub Actions issue is something I meant to do a few days ago but got lazy, many thanks! The same issue also arises in different OS builds (see [this issue](https://github.com/ipeaGIT/aopdata/issues/25) in `{aopdata}`, for example), which leads me to believe that this deserves a bit more thought in the future (it's probably not failing here due to package caching in the other builds, I guess). Shouldn't be hard to fix, basically applying this same fix of yours to ubuntu should do it... Well, I digress. This is a future me problem :)

Thanks again!

**Comment by dhersz** [comment]
Ok, I stand corrected. The ubuntu failure in `{aopdata}` doesn't seem related to `units`. Even better!

**Pull request merged**
