### PR TITLE
add new function filter_route_id(). Closes #11

### LINKED ISSUE #11: merge filter_route_id() from gfs2gps

### PR DESCRIPTION
**Pull request by rafapereirabr**
add new function `filter_route_id()` and tests. Closes #11

### CODE REVIEW

**Comment by dhersz** [comment]
Hi Rafa, I see a few things:

The check returns some notes:

```
 * checking R code for possible problems ... NOTE
filter_route_id: no visible binding for global variable ‘route_id’
filter_route_id: no visible binding for global variable ‘trip_id’
filter_route_id: no visible binding for global variable ‘stop_id’
filter_route_type: no visible binding for global variable ‘route_type’
filter_route_type: no visible binding for global variable ‘route_id’
filter_route_type: no visible binding for global variable ‘trip_id’
filter_route_type: no visible binding for global variable ‘stop_id’
Undefined global functions or variables:
  route_id route_type stop_id trip_id
```

This can be fixed by adding the name of these columns to the `utils::globalVariables()` call in `R/gtfstools.R`.

It also resulted in an error:

```
* checking examples ... ERROR
Error: Running examples in ‘gtfstools-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: filter_route_id
> ### Title: Filter GTFS data by route ids
> ### Aliases: filter_route_id
> 
> ### ** Examples
> 
> # read gtfs
> data_path <- system.file("extdata/spo_gtfs.zip", package = "gtfstools")
> gtfs <- read_gtfs(data_path)
> 
> # filter: Keep selected routes
> subset1 <- filter_route_id(gtfs, route_ids=c("6450-51", "CPTM L11"), keep = T)
Error: Error in checkmate::assert_logical(keep) : T used instead of TRUE
```

Apparently `{checkmate}` doesn't accept `T` instead of `TRUE`.

Do you mind fixing these bits, please? Thanks!

**Comment by pedro-andrade-inpe** [comment]
> Apparently {checkmate} doesn't accept T instead of TRUE.

This is really good, as CRAN reviewers also do not like T/F.

**Comment by rafapereirabr** [comment]
Thanks for the heads up. Fixing it now.

**Comment by dhersz** [comment]
Great Rafa! Thanks!

**Pull request merged**
